# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HealthSource' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealthSource
    pod 'SSZipArchive', '~> 2.1'
    pod 'SwiftyDropbox', '~> 4.3'
    pod 'ReachabilitySwift', '~> 4.1'
    pod 'NVActivityIndicatorView', '~> 4.1'

  target 'HealthSourceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HealthSourceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'shareExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shareExtension

end
